// Self-host the Rubik font: fetch Google Fonts' CSS, download the woff2 files
// (Hebrew + Latin subsets, the weights the app uses) into public/fonts/, and
// emit src/styles/fonts.css with local @font-face rules. This makes the brand
// font work offline, removes a render-blocking third-party request, and drops
// the Google dependency. Re-run only if the weight set changes.
import { mkdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
// Fonts live under src/ so Vite bundles + fingerprints them and rewrites the
// url() with the deploy base (works at root AND on a Pages subpath).
const FONT_DIR = join(ROOT, "src", "styles", "fonts");
mkdirSync(FONT_DIR, { recursive: true });

const WEIGHTS = [400, 500, 600, 700, 800, 900];
const KEEP_SUBSETS = ["hebrew", "latin"]; // app is Hebrew + some Latin (HIIT/WOD/numbers)
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36";

const cssUrl = `https://fonts.googleapis.com/css2?family=Rubik:wght@${WEIGHTS.join(";")}&display=swap`;
console.log("Fetching Google Fonts CSS…");
const css = await (await fetch(cssUrl, { headers: { "User-Agent": UA } })).text();

// Each @font-face is preceded by a `/* subset */` comment.
const blocks = css.split("/*").slice(1);
const faces = [];
for (const raw of blocks) {
  const subset = raw.slice(0, raw.indexOf("*/")).trim();
  if (!KEEP_SUBSETS.includes(subset)) continue;
  const body = raw.slice(raw.indexOf("*/") + 2);
  const weight = body.match(/font-weight:\s*(\d+)/)?.[1];
  const url = body.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
  const range = body.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();
  if (weight && url && range) faces.push({ subset, weight, url, range });
}
console.log(`  ${faces.length} @font-face blocks (${KEEP_SUBSETS.join(", ")})`);

// Google serves Rubik as a variable font: the woff2 is identical across weights
// for a given subset. Emit ONE @font-face per subset with a weight RANGE — the
// correct, cross-browser-robust way to declare a variable font.
const out = [];
for (const subset of KEEP_SUBSETS) {
  const f = faces.find((x) => x.subset === subset);
  if (!f) continue;
  const name = `rubik-${subset}.woff2`;
  const buf = Buffer.from(await (await fetch(f.url, { headers: { "User-Agent": UA } })).arrayBuffer());
  writeFileSync(join(FONT_DIR, name), buf);
  console.log(`  ✓ ${name} (${(buf.length / 1024).toFixed(1)}kb)`);
  out.push(
    `@font-face {\n  font-family: "Rubik";\n  font-style: normal;\n  font-weight: ${Math.min(...WEIGHTS)} ${Math.max(...WEIGHTS)};\n  font-display: swap;\n  src: url("./fonts/${name}") format("woff2");\n  unicode-range: ${f.range};\n}`,
  );
}

const header =
  "/* Self-hosted Rubik (Hebrew + Latin). Generated by scripts/gen-fonts.mjs.\n" +
  "   Local fonts => works offline, no render-blocking third-party request. */\n\n";
writeFileSync(join(ROOT, "src", "styles", "fonts.css"), header + out.join("\n\n") + "\n");
console.log(`\nWrote src/styles/fonts.css (${out.length} faces). Done.`);
